/**
 * Shipping applicability, charge-type, and visibility domain constants.
 * Applicability = whether shipping applies; charge type = how it is charged;
 * visibility = whether the shopper sees shipping as a separate purchase element.
 */

const SHIPPING_APPLICABILITY_INHERIT = 'inherit';
const SHIPPING_APPLICABILITY_APPLICABLE = 'applicable';
const SHIPPING_APPLICABILITY_NOT_APPLICABLE = 'not_applicable';

const CATALOG_SHIPPING_APPLICABILITY_VALUES = [
  SHIPPING_APPLICABILITY_INHERIT,
  SHIPPING_APPLICABILITY_APPLICABLE,
  SHIPPING_APPLICABILITY_NOT_APPLICABLE,
];

const EFFECTIVE_SHIPPING_APPLICABILITY_VALUES = [
  SHIPPING_APPLICABILITY_APPLICABLE,
  SHIPPING_APPLICABILITY_NOT_APPLICABLE,
];

const SHIPPING_TYPE_INHERIT = 'inherit';
const SHIPPING_TYPE_FREE = 'free';
const SHIPPING_TYPE_FLAT = 'flat';
const SHIPPING_TYPE_STANDARD = 'standard';
const SHIPPING_TYPE_VARIABLE = 'variable';

const CATALOG_SHIPPING_TYPE_VALUES = [
  SHIPPING_TYPE_INHERIT,
  SHIPPING_TYPE_FREE,
  SHIPPING_TYPE_FLAT,
  SHIPPING_TYPE_STANDARD,
  SHIPPING_TYPE_VARIABLE,
];

const EFFECTIVE_SHIPPING_TYPE_VALUES = [
  SHIPPING_TYPE_FREE,
  SHIPPING_TYPE_FLAT,
  SHIPPING_TYPE_STANDARD,
  SHIPPING_TYPE_VARIABLE,
];

/** Order-level cart profile after resolution */
const ORDER_SHIPPING_APPLICABILITY_FULL = 'full';
const ORDER_SHIPPING_APPLICABILITY_PARTIAL = 'partial';
const ORDER_SHIPPING_APPLICABILITY_NONE = 'none';

const ORDER_SHIPPING_APPLICABILITY_VALUES = [
  ORDER_SHIPPING_APPLICABILITY_FULL,
  ORDER_SHIPPING_APPLICABILITY_PARTIAL,
  ORDER_SHIPPING_APPLICABILITY_NONE,
];

const SHIPPING_RESOLUTION_SOURCES = [
  'product',
  'childCategory',
  'subcategory',
  'category',
  'platform_default',
];

const SHIPPING_VISIBILITY_INHERIT = 'inherit';
const SHIPPING_VISIBILITY_SHOW = 'show';
const SHIPPING_VISIBILITY_HIDE = 'hide';

const CATALOG_SHIPPING_VISIBILITY_VALUES = [
  SHIPPING_VISIBILITY_INHERIT,
  SHIPPING_VISIBILITY_SHOW,
  SHIPPING_VISIBILITY_HIDE,
];

const EFFECTIVE_SHIPPING_VISIBILITY_VALUES = [
  SHIPPING_VISIBILITY_SHOW,
  SHIPPING_VISIBILITY_HIDE,
];

/** Cart visibility profile after resolution (shopper presentation) */
const ORDER_SHIPPING_VISIBILITY_NONE = 'visibility_none';
const ORDER_SHIPPING_VISIBILITY_ALL_HIDE = 'visibility_all_hide';
const ORDER_SHIPPING_VISIBILITY_ALL_SHOW = 'visibility_all_show';
const ORDER_SHIPPING_VISIBILITY_MIXED = 'visibility_mixed';

const ORDER_SHIPPING_VISIBILITY_PROFILE_VALUES = [
  ORDER_SHIPPING_VISIBILITY_NONE,
  ORDER_SHIPPING_VISIBILITY_ALL_HIDE,
  ORDER_SHIPPING_VISIBILITY_ALL_SHOW,
  ORDER_SHIPPING_VISIBILITY_MIXED,
];

const PLATFORM_DEFAULT_SHIPPING_APPLICABILITY = SHIPPING_APPLICABILITY_APPLICABLE;
const PLATFORM_DEFAULT_SHIPPING_TYPE = SHIPPING_TYPE_STANDARD;
const PLATFORM_DEFAULT_SHIPPING_VISIBILITY = SHIPPING_VISIBILITY_SHOW;

/** Shipping engine / order method when no lines require physical shipping */
const SHIPPING_METHOD_NOT_APPLICABLE = 'not_applicable';

/** Legacy orders without shippingApplicability snapshot are treated as full. */
const LEGACY_ORDER_SHIPPING_APPLICABILITY = ORDER_SHIPPING_APPLICABILITY_FULL;

/** Legacy order lines without shippingVisibility snapshot are treated as show. */
const LEGACY_LINE_SHIPPING_VISIBILITY = SHIPPING_VISIBILITY_SHOW;

module.exports = {
  SHIPPING_APPLICABILITY_INHERIT,
  SHIPPING_APPLICABILITY_APPLICABLE,
  SHIPPING_APPLICABILITY_NOT_APPLICABLE,
  CATALOG_SHIPPING_APPLICABILITY_VALUES,
  EFFECTIVE_SHIPPING_APPLICABILITY_VALUES,
  SHIPPING_TYPE_INHERIT,
  SHIPPING_TYPE_FREE,
  SHIPPING_TYPE_FLAT,
  SHIPPING_TYPE_STANDARD,
  SHIPPING_TYPE_VARIABLE,
  CATALOG_SHIPPING_TYPE_VALUES,
  EFFECTIVE_SHIPPING_TYPE_VALUES,
  ORDER_SHIPPING_APPLICABILITY_FULL,
  ORDER_SHIPPING_APPLICABILITY_PARTIAL,
  ORDER_SHIPPING_APPLICABILITY_NONE,
  ORDER_SHIPPING_APPLICABILITY_VALUES,
  SHIPPING_RESOLUTION_SOURCES,
  PLATFORM_DEFAULT_SHIPPING_APPLICABILITY,
  PLATFORM_DEFAULT_SHIPPING_TYPE,
  SHIPPING_METHOD_NOT_APPLICABLE,
  LEGACY_ORDER_SHIPPING_APPLICABILITY,
  SHIPPING_VISIBILITY_INHERIT,
  SHIPPING_VISIBILITY_SHOW,
  SHIPPING_VISIBILITY_HIDE,
  CATALOG_SHIPPING_VISIBILITY_VALUES,
  EFFECTIVE_SHIPPING_VISIBILITY_VALUES,
  ORDER_SHIPPING_VISIBILITY_NONE,
  ORDER_SHIPPING_VISIBILITY_ALL_HIDE,
  ORDER_SHIPPING_VISIBILITY_ALL_SHOW,
  ORDER_SHIPPING_VISIBILITY_MIXED,
  ORDER_SHIPPING_VISIBILITY_PROFILE_VALUES,
  PLATFORM_DEFAULT_SHIPPING_VISIBILITY,
  LEGACY_LINE_SHIPPING_VISIBILITY,
};
